"""
Central Prometheus metrics definition for ProphitBet SaaS domain operations.
"""

from prometheus_client import Counter, Gauge, Histogram

# Celery Task & Background Job Metrics
CELERY_TASK_EXECUTED = Counter(
    "prophitbet_celery_task_executed_total",
    "Total executions of Celery tasks",
    ["task_name", "status"]
)

CELERY_TASK_DURATION = Histogram(
    "prophitbet_celery_task_duration_seconds",
    "Duration of Celery task executions in seconds",
    ["task_name"],
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0)
)

# Soccer Prediction Metrics
PREDICTIONS_GENERATED = Counter(
    "prophitbet_predictions_generated_total",
    "Total soccer predictions generated by ML models",
    ["league", "market"]
)

# SA Odds & Scraping Metrics
SA_ODDS_SCRAPED = Counter(
    "prophitbet_sa_odds_scraped_total",
    "Total South Africa bookmaker odds scraped/updated",
    ["bookmaker", "market"]
)

# Live Match Metrics
LIVE_MATCHES_ACTIVE = Gauge(
    "prophitbet_live_matches_active",
    "Number of currently active live soccer matches being tracked"
)

# Vector RAG & AI Metrics
VECTOR_RAG_QUERIES = Counter(
    "prophitbet_vector_rag_queries_total",
    "Total queries processed by Qdrant Vector RAG engine",
    ["status"]
)
